name: 'DK Git Salesforce Authentication'
description: 'Authentication Salesforce using credential and getting response oauth2 : token '

inputs:
  user_name:
    required: true
    type: string
  login_url:
    type: string
    default: https://login.salesforce.com
  password:
    required: true
    description: combination of <password>:<security_token>
  sfdc_client_id:
    required: true
    description: Consumer Key of a connected App created within salesforce
  sfdc_client_secret:
    required: true
    description: Consumer Secret of a connected App created within salesforce

# Mapping the workflow outputs with job outputs
outputs:
  access_token:
    description: "The first output string"
    value: ${{ jobs.sfdc_auth.outputs.access_token }}
  instance_url:
    description: "The second output string"
    value: ${{ jobs.sfdc_auth.outputs.instance_url }}
  id:
    description: "The first output string"
    value: ${{ jobs.sfdc_auth.outputs.id }}
  error:
    description: "The second output string"
    value: ${{ jobs.sfdc_auth.outputs.error }}
  error_description:
    description: "The second output string"
    value: ${{ jobs.sfdc_auth.outputs.error_description }}

runs:
  using: "composite"
  steps:
    - name: Dispaly inputs
      shell: bash
      run: |
        echo Hello ${{ inputs.user_name }}.
        echo Hello ${{ inputs.login_url }}.
    - id: sfdc_rest_call
      name: Authenticating User using Rest call
      run: |
        echo Hello ${{ inputs.user_name }}.
        echo Hello ${{ inputs.login_url }}.