on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: DK Git Salesforce CLI Configuration
        id: sfdc
        uses: karamchandanid/sfdc-credentials-auth@v10
        with:
          user_name: dharmendra.karamchandani@gmail.com
          instance_url: test.com
          password: combination
          sfdc_client_id: Consumer Key
          sfdc_client_secret: Consumer secret
      - uses: actions/checkout@v3
      - run: |
          echo dharmendra.karamchandani@gmail.com
          echo using v10
        shell: bash
